apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-k8s-dotnet
spec:
  selector:
    matchLabels:
      app: hello-world-k8s-dotnet
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world-k8s-dotnet
    spec:
      containers:
        - name: hello-world-k8s-dotnet
          image: stwomack/dotnet:hello-world-k8s-dotnet
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
          envFrom:
            - configMapRef:
                name: helloworld-configs
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-k8s-dotnet
spec:
  type: LoadBalancer
  selector:
    app: hello-world-k8s-dotnet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
